apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment-autoscaling
  labels:
    app: my-k8s-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      project: xyz
  template:
    metadata:
      labels:
        project: xyz # Service will look for those pods labels!!!
    spec:
      containers:
        - name: xyz-php
          image: tsar36/app-php:latest
          resources:
            limits:
              cpu: 200m
              memory: 500Mi
          ports:
            - containerPort: 80

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: my-autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: web-deployment-autoscaling
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50

---
apiVersion: v1
kind: Service
metadata:
  name: web-deployment-autoscaling
  namespace: default
  labels:
    env: prod
    owner: TsaR
spec:
  selector:
    project: xyz
  type: LoadBalancer
  ports:
    - name: app-listener
      protocol: TCP
      port: 80
      targetPort: 80
      # If you set the `spec.type` field to `NodePort` and you want a specific port number,
      # you can specify a value in the `spec.ports[*].nodePort` field.
