apiVersion: apps/v1
kind: Deployment
metadata:
  name:  hello-world-deployment
  namespace: default
  labels:
    app:  helloworld
spec:
  selector:
    matchLabels:
      app: helloworld
  replicas: 3
  # strategy:
  #   rollingUpdate:
  #     maxSurge: 25%
  #     maxUnavailable: 25%
  #   type: RollingUpdate
  template:
    metadata:
      labels:
        app:  helloworld
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  k8s-php
        image:  tsar36/app-php:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 1234
          name:  php-port