# Use secrets as environment variable.
# Use secrets as a file in a pod. This setup uses volumes to be mounted in a container which has files.
# Use an external image to pull secrets (from private image registry).
# To generate secrets using files: $ echo -n "root" > ./username.txt | echo -n "password" > ./pass.txt
# A secret can also be an SSH-key or SSL cert.: $ kubectl create secret generic ssl-certificate --from-file=ssh-privatekey=~/.ssh/id_rsa --ssl-cert=mysslcert.crt

apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  namespace: default
type: Opaque
data:
#  password: {{ .Values.password | b64enc }} | or | cm9vdA== (<< echo -n "root" | base64)
#  username: cGFzc3dvmbQ== | << echo -n "password" | base64