apiVersion: v1
kind: Service

metadata:
  name: web-service

spec:
  ports:
    - name: http
      port: 80
  selector:
    app: web
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: web-deployment

spec:
  replicas: 2
  selector:
    matchLabels:
      app: web

  template:
    metadata:
      labels:
        app: web

    spec:
      containers:
        - image: nginx:1.14.2
          name: nginx
          resources:
            limits:
              cpu: 200m
              memory: 500Mi
          requests:
            cpu: 100m
            memory: 200Mi
            ports:
              - containerPort: 80
