apiVersion: apps/v1
kind: Deployment
metadata:
  name:  hpa-example
  namespace: default
  labels:
    app: hpa-example
spec:
  selector:
    matchLabels:
      app: hpa-example
  replicas: 3
  template:
    metadata:
      labels:
        app: hpa-example
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  hpa-example
        image: gcr.io/google_containers/hpa-example
        ports:
        - name: http-port
          containerPort: 80
        resources:
          requests:
            cpu: 200m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 100Mi