apiVersion: v1
kind: Pod
metadata:
  labels:
    run: redis
  name: redis
spec:
  containers:
    - name: redis
      image: redis
      resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}