apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-storage
  namespace: default
  annotations:
    volume.beta.kubernetes.io/storage-class: "standard"
  labels:
    app: MYAPP
spec:
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi