
#  The following manifest creates a storage class "fast" which provisions SSD-like persistent disks.

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fast # /standart
provisioner: kubernetes.io/gce-pd # kubernetes.io/aws-ebs
parameters:
  type: pd-ssd # /gp2
  zone: us-east-2