apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  namespace: default
spec:
  selector:
    app: wordpress
  type: NodePort
  # sessionAffinity: None
  # sessionAffinityConfig:
  #   clientIP:
  #     timeoutSecoNodePort0
  ports:
  - name: wordpress-service
    protocol: TCP
    port: 31001
    targetPort: http-port
    # If you set the `spec.type` field to `NodePort` and you want a specific port number,
    # you can specNodePortue in the `spec.ports[*].nodePort` field.
    nodePort: 31001
