apiVersion: apps/v1
kind: Deployment
metadata:
  name:  docker-nodejs-demo
  namespace: demo
  labels:
    app:  docker-nodejs-demo
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.docker-nodejs-demo: semver:~1.0.0
spec:
  selector:
    matchLabels:
      app: docker-nodejs-demo
  replicas: 1
  strategy:
    rollingUpdate:
      # maxSurge: 25%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  docker-nodejs-demo
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  docker-nodejs-demo
        image:  wardviaene/docker-nodejs-demo:1.0.1
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        # livenessProbe:
        #   tcpSocket:
        #     port: 80
        #   initialDelaySeconds: 5
        #   timeoutSeconds: 5
        #   successThreshold: 1
        #   failureThreshold: 3
        #   periodSeconds: 10
        # readinessProbe:
        #   httpGet:
        #     path: /_status/healthz
        #     port: 80
        #   initialDelaySeconds: 5
        #   timeoutSeconds: 2
        #   successThreshold: 1
        #   failureThreshold: 3
        #   periodSeconds: 10
        # env:
        # - name: DB_HOST
        #   valueFrom:
        #     configMapKeyRef:
        #       name: MYAPP
        #       key: DB_HOST
        ports:
        - containerPort:  3000
          name:  nodejs-port
      #   volumeMounts:
      #   - name: localtime
      #     mountPath: /etc/localtime
      # volumes:
      #   - name: localtime
      #     hostPath:
      #       path: /usr/share/zoneinfo/Asia/Shanghai
      # restartPolicy: Always