apiVersion: v1
kind: Service
metadata:
  name: docker-nodejs-demo
  namespace: demo
spec:
  selector:
    app: docker-nodejs-demo
  type: NodePort
  # sessionAffinity: None
  # sessionAffinityConfig:
  #   clientIP:
  #     timeoutSeconds: 10800
  ports:
  - name: nodejs-port
    protocol: TCP
    port: 80
    targetPort: nodejs-port
    # If you set the `spec.type` field to `NodePort` and you want a specific port number,
    # you can specify a value in the `spec.ports[*].nodePort` field.
    nodePort: 80