apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: python-multistep-workflow
spec:
  entrypoint:
  templates:
  - name: python-multistep-workflow
    steps:
    - - name: step-1
        template: python-print
        arguments:
          parameters:
          - name: message
            value: "Hello, this is step-1..."
    - - name: step-2
        template: python-print
        arguments:
          parameters:
          - name: message
            value: "Hello, this is step-2..."
    - - name: step-3
        template: python-print
        arguments:
          parameters:
          - name: message
            value: "Hello, this is step-3..."
  - name: python-print
    inputs:
      parameters:
      - name: message
    container:
      image: python:3.7
      command: [python, -c, import sys;print(sys.argv)]
      args: ["{{inputs.parameters.message}}"]