apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: python-multisteps-
spec:
  entrypoint: main-workflow
  templates:
  - name: main-workflow
    steps:
    - - name: step1
        template: step1-template
    - - name: step2
        template: step2-template

  - name: step1-template
    container:
      image: python:3.8
      command: ["python", "-c"]
      args: ["print('Step 1')"]

  - name: step2-template
    container:
      image: python:3.8
      command: ["python", "-c"]
      args: ["print('Step 2')"]